version: "3.7"
services:
  app:
    # container_name: dockerized-node-app
    image: node:12-alpine
    command: sh -c "yarn install &&  yarn start"
    # build: ./
    # restart: always
    working_dir: /app

    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - ignore:/app/node_modules

volumes:
  ignore:
